# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Sinclair Intent
version: "0.0.3"
slug: sinclair_intent
description: Custom Rhasspy intent handler for Sinclair
url: "https://github.com/DavidMikeSimon/sinclair/tree/main/sinclair_intent"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options: {}
schema: {}
homeassistant_api: true
#image: "ghcr.io/DavidMikeSimon/{arch}-sinclair-intent"
