name: Sinclair Intent
version: "0.0.13"
slug: sinclair_intent
description: Custom Rhasspy intent handler for Sinclair
url: "https://github.com/DavidMikeSimon/sinclair-home-assistant-addons"
image: "ghcr.io/davidmikesimon/{arch}-sinclair-intent"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
homeassistant_api: true
services:
  - "mqtt:need"
